Linux:
g++ -I. bayer.cpp VidHeader.cpp -lz read-frame.cpp main.cpp showErrMsgBox.cpp -o ./bin/vidReader

Windows:
g++ -I. bayer.cpp VidHeader.cpp -lz read-frame.cpp main.cpp showErrMsgBox.cpp -o ./bin/vidReader.exe
